export enum Emojo {
  LOG = "📄",
  IF = "🤔",
  ELSE = "🤨",
  EQUALS = "🟰",
  PLUS = "➕",
  MINUS = "➖",
  TIMES = "✖️",
  DIVISION = "➗",
  BIGGER_THAN = "🫴",
  LESS_THAN = "🫳",
  RETURN = "😎",
  OPEN_PARENTHESIS = "🌜",
  CLOSE_PARENTHESIS = "🌛",
  OPEN_CURLY = "👉",
  CLOSE_CURLY = "👈",
  QUOTES = "🍃",
  SEMI = "✅",
  CONST = "🔴",
  VAR = "🟠",
  LET = "🟢",
  DOT = "🔹",
};
